apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: argocd
resources:
  - https://raw.githubusercontent.com/argoproj/argo-cd/v2.0.5/manifests/install.yaml
  - ingress.yaml
  - namespace.yaml
patchesStrategicMerge:
  - patch_deployment.yaml
